### ISSUE TITLE
Cool Project!

### ISSUE THREAD

**Issue by aj-foster** [marmelasoft/openapi_codegen#15]
Hi there 👋🏼 

Just stopping by to say that this is a cool project, and I hope it goes well! I worked on [something similar](https://github.com/aj-foster/open-api-generator), and if there's any way it can help, that's great.

Best of luck! (You can close this. 🙂)

**Comment by nelsonmestevao** [comment]
Thank you 🤩 

Your project seems awesome! We probably have similar goals, and could benefit from each other! I hope both can contribute to the Elixir Ecosystem 🚀

**Comment by aj-foster** [comment]
❤️
